### ISSUE TITLE
sync and other task do not work when replacing the salt master node

### ISSUE THREAD

**Issue by tim-mcarthur-moj** [ministryofjustice/opg-cotton#25]
When replacing the master node, the default user (ubuntu) which is used for the initial connection cannot be used as it no longer exists on the jump host.

This can be fixed by allowing different usernames for the jump and master connections.

**Comment by brettminnie** [comment]
This was due to the implementation in the fabfile @tim-mcarthur-moj  can you confirm and can we mark this as closed

**Comment by tim-mcarthur-moj** [comment]
This has been tested and works correctly for the ssh connection.  This does not however address the  need to remove the master public key from existing  minions, and restart the minions service to work with the new master node.

**Comment by brettminnie** [comment]
Cheers I've flagged that on the current ticket, see if I can wrap that in
