### ISSUE TITLE
support for multiple salt environments on a single master

### ISSUE THREAD

**Issue by tim-mcarthur-moj** [ministryofjustice/opg-cotton#26]
Salt support the concept of environments which allow multiple distinct sets of pillar and salt root directories.

Cotton needs to support this extended directory layout and configuration.

**Comment by brettminnie** [comment]
* Try reload config without restarting the master
 * On master restart remove pub/ping file from all minions (new state)

**Comment by brettminnie** [comment]
Possibly we only need to do the pillar
See if salt/master supports a yaml include

**Comment by brettminnie** [comment]
Salt formulas are per project so we do not need to all targetting unless we start sharing projects across the board
